// Frontend state. Replace sendMessageToBackend when the Flask API is ready.
const chatForm = document.getElementById('chatForm');
const messageInput = document.getElementById('messageInput');
const messages = document.getElementById('messages');
const typingIndicator = document.getElementById('typingIndicator');
const languageSelect = document.getElementById('languageSelect');
const composerLanguage = document.getElementById('composerLanguage');
const toast = document.getElementById('toast');
const micButton = document.getElementById('micButton');
const themeToggle = document.getElementById('themeToggle');
let latestAiText = "Hello! I'm AI Life Navigator. Tell me what you are trying to solve, understand, plan or decide.";
let lastUserMessage = '';
let speakingButton = null;
let recognition = null;
const language = { code: 'en', label: 'English', speech: 'en-US' };
function showToast(text) { toast.textContent = text; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 3200); }
function setTypingVisible(visible) { typingIndicator.hidden = !visible; typingIndicator.style.display = visible ? 'flex' : 'none'; }
function createAction(icon, label, action) { const button = document.createElement('button'); button.type = 'button'; button.className = 'message-action'; button.textContent = icon; button.title = label; button.setAttribute('aria-label', label); button.addEventListener('click', action); return button; }
function speakText(text, button) { if (!('speechSynthesis' in window)) { showToast('Text-to-speech is not supported in this browser.'); return; } if (speakingButton === button && speechSynthesis.speaking) { speechSynthesis.cancel(); button.classList.remove('active'); speakingButton = null; return; } speechSynthesis.cancel(); if (speakingButton) speakingButton.classList.remove('active'); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = language.speech; utterance.onend = () => { button.classList.remove('active'); speakingButton = null; }; speechSynthesis.speak(utterance); button.classList.add('active'); speakingButton = button; }
function createMessageTools(text) { const tools = document.createElement('div'); tools.className = 'message-tools'; tools.append(createAction('[copy]', 'Copy response', () => { navigator.clipboard?.writeText(text); showToast('Response copied to your clipboard.'); }), createAction('[speak]', 'Read response aloud', (event) => speakText(text, event.currentTarget)), createAction('[again]', 'Regenerate response', regenerateResponse)); return tools; }
function addMessage(text, sender) { const row = document.createElement('div'); row.className = `message-row ${sender === 'user' ? 'user-row' : 'ai-row'}`; const avatar = document.createElement('span'); avatar.className = 'message-avatar'; avatar.textContent = sender === 'user' ? 'You' : '*'; const bubble = document.createElement('div'); bubble.className = `message ${sender === 'user' ? 'user-message' : 'ai-message'}`; const paragraph = document.createElement('p'); paragraph.textContent = text; const time = document.createElement('time'); time.textContent = sender === 'user' ? 'Just now' : 'MOCK response - Just now'; bubble.append(paragraph, time); if (sender === 'ai') bubble.append(createMessageTools(text)); row.append(avatar, bubble); messages.appendChild(row); messages.scrollTop = messages.scrollHeight; if (sender === 'ai') latestAiText = text; }
// Future API boundary: send { message, language, conversation_id } to POST /api/chat.
async function sendMessageToBackend(message, languageCode) {
  const response = await fetch('http://127.0.0.1:5000/api/chat', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message, language: languageCode, conversation_id: 'demo-001' })
  });

  if (!response.ok) throw new Error(`Chat request failed with status ${response.status}.`);
  return response.json();
}
async function sendMessage(event) { event?.preventDefault(); const text = messageInput.value.trim(); if (!text) return; lastUserMessage = text; addMessage(text, 'user'); messageInput.value = ''; messageInput.style.height = 'auto'; setTypingVisible(true); try { const result = await sendMessageToBackend(text, language.code); addMessage(result.response, 'ai'); } catch (error) { showToast('Could not reach Flask. Make sure the backend is running.'); console.error(error); } finally { setTypingVisible(false); } }
async function regenerateResponse() { if (!lastUserMessage) return; setTypingVisible(true); try { const result = await sendMessageToBackend(lastUserMessage, language.code); addMessage(result.response, 'ai'); showToast('A fresh Flask response is ready.'); } catch (error) { showToast('Could not reach Flask. Make sure the backend is running.'); console.error(error); } finally { setTypingVisible(false); } }
function setupVoiceInput() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { showToast('Voice input is not supported in this browser. You can still type your message.'); return; } if (recognition) { recognition.stop(); return; } recognition = new SpeechRecognition(); recognition.lang = language.speech; recognition.interimResults = true; recognition.continuous = false; recognition.onstart = () => { micButton.classList.add('listening'); micButton.setAttribute('aria-label', 'Stop voice input'); showToast('Listening locally. Speak your question now.'); }; recognition.onresult = (event) => { messageInput.value = Array.from(event.results).map((result) => result[0].transcript).join(''); messageInput.dispatchEvent(new Event('input')); }; recognition.onerror = () => showToast('Voice input could not start. Please check your browser microphone permission.'); recognition.onend = () => { micButton.classList.remove('listening'); micButton.setAttribute('aria-label', 'Start voice input'); recognition = null; }; recognition.start(); }
function setTheme(theme) { document.documentElement.dataset.theme = theme; localStorage.setItem('aiLifeTheme', theme); const dark = theme === 'dark'; themeToggle.querySelector('.theme-icon').textContent = dark ? 'L' : 'D'; themeToggle.setAttribute('aria-label', dark ? 'Switch to light mode' : 'Switch to dark mode'); }
chatForm.addEventListener('submit', sendMessage); micButton.addEventListener('click', setupVoiceInput); document.getElementById('composerSpeakButton').addEventListener('click', (event) => speakText(latestAiText, event.currentTarget)); document.getElementById('attachmentButton').addEventListener('click', () => showToast('Attachments are planned for a future version.')); languageSelect.addEventListener('change', () => { languageSelect.value = 'en'; composerLanguage.textContent = language.label; showToast('English is currently the only supported language.'); }); document.querySelectorAll('[data-question]').forEach((button) => button.addEventListener('click', () => { messageInput.value = button.dataset.question; messageInput.dispatchEvent(new Event('input')); document.getElementById('chat').scrollIntoView({ behavior: 'smooth', block: 'start' }); setTimeout(() => messageInput.focus(), 450); })); messageInput.addEventListener('input', () => { messageInput.style.height = 'auto'; messageInput.style.height = `${Math.min(messageInput.scrollHeight, 86)}px`; }); themeToggle.addEventListener('click', () => setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'));
setTheme(localStorage.getItem('aiLifeTheme') || 'light'); composerLanguage.textContent = language.label; languageSelect.value = language.code;
const menuToggle = document.getElementById('menuToggle'); const navLinks = document.getElementById('navLinks'); menuToggle.addEventListener('click', () => { const open = navLinks.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', open); menuToggle.setAttribute('aria-label', open ? 'Close navigation menu' : 'Open navigation menu'); }); navLinks.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { navLinks.classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false'); }));